### ISSUE TITLE
In dual tracking setup GA4 EEC to Universal Analytics EEC Convertor returns null

### ISSUE THREAD

**Issue by ackoot** [gtm-templates-knowit-experience/ga4-ecom-to-eec-converter#1]
Hi, 

Did Anyone have an issue with the GA4 EEC to Universal Analytics EEC Convertor in dual GA4+UA EEC tracking setup?
At the time of the view_item event data returned by the convertor is valid (see screenshot 1).
But in the UA tag firing overview ‘Read Data From variable’ shows `null` (see screenshot 2).

Note:

1. The partner GA4 view_item tag  on the same event contains value EEC data.
2. If I manually push the view_item event with exactly the same GA4 EEC dataLayer information, the UA tags does get successfully the converted Universal Analytics EEC schema object (see screenshot 3).
3. Tag priority or Tag sequencing or pausing the GA4 view_item tag did not make a difference
4. The GTM4WP Plug-in is used by the web dev to render the dataLayer.

Any response I greatly appreciated.

Thank you.

Kind regards,

Andre
![screenshot_1](https://user-images.githubusercontent.com/13680599/138090847-9eb30c97-93c2-4376-9599-9d5f6effcf5d.png)
![screenshot2](https://user-images.githubusercontent.com/13680599/138091017-6866ae1a-0dca-4ff3-bea8-6aa8eaa2338f.png)
![screenshot_3](https://user-images.githubusercontent.com/13680599/138091098-1fa18c48-0f74-409d-acd3-95806bfa9325.png)

**Comment by EivindSavio** [comment]
Since there are some days since you asked the question, have you figured it out?

I have tested with the GTM4WP Plug-in, and can't reproduce the issue. 
![image](https://user-images.githubusercontent.com/73120783/142495303-3fd80cb4-f99c-4d91-b50c-cf69438425af.png)
