### ISSUE TITLE
Allow for events without ecommerce.items

### ISSUE THREAD

**Issue by harmtemolder** [gtm-templates-knowit-experience/ga4-ecom-to-eec-converter#4]
Some events (e.g. [`checkout`](https://developers.google.com/analytics/devguides/collection/ua/gtm/enhanced-ecommerce#checkout)) don't require any product information. From how I read your code you do require `ecommerce.items` for all events: https://github.com/gtm-templates-knowit-experience/ga4-ecom-to-eec-converter/blob/main/template.tpl#L415

**Comment by EivindSavio** [comment]
Fixed.
